### ISSUE TITLE
Support relative positioning

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#223]
I think it's a bit limiting that the viewer and the control panel assumes it's the first element in the entire page and use absolute position. For example, this is not compatible with the following UI layout:
![Screen Shot 2020-01-22 at 2 48 52 PM](https://user-images.githubusercontent.com/478667/72899448-53ab2c80-3d26-11ea-9071-c7881c81a14a.png)

And I had to add the following css to get around of it:
```css
#viewer > div:nth-child(2) {
  top: 64px!important;
}

#viewer > div:first-child {
  height: calc(100vh - 64px)!important;
  min-height: 100px!important;
}
```
Such that it looks like this:

![Screen Shot 2020-01-22 at 2 53 02 PM](https://user-images.githubusercontent.com/478667/72899765-f663ab00-3d26-11ea-8d7b-f2566122c3fa.png)
